version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/reporting-rshiny-macrobenthos
hooks:
  AfterInstall:
    - location: scripts/reporting-rshiny-macrobenthos.sh
      timeout: 1000
permissions:
  - object: /home/ubuntu/reporting-rshiny-macrobenthos
    owner: ubuntu
    group: ubuntu
mode: 764